<a href="https://colab.research.google.com/github/Li-Thao-Phung/Pytorch-Tutorial-Youtube/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8,])

In [6]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [9]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [10]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [12]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [13]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [16]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [18]:
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [19]:
tensor_a

tensor([11, 14, 17, 20])