<a href="https://colab.research.google.com/github/Li-Thao-Phung/Pytorch-Tutorial-Youtube/blob/main/Tensors_t.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [ ]:
np1 = np.random.rand(3,4)
np1
np1.dtype


dtype('float64')

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.9160, -0.8759, -0.7909, -0.3352],
        [ 0.4790, -1.0593,  2.3609,  0.4597],
        [ 0.3060, -0.4934,  1.3670,  2.1945]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7248, 0.1218, 0.2997, 0.2395],
        [0.1380, 0.7288, 0.4174, 0.2988],
        [0.2650, 0.8749, 0.8148, 0.2612]], dtype=torch.float64)